I'm sorry, but an uncaught exception occurred.

While parsing D:\DCT_A_new_Journey_begin_1.1.4/game/Code - 1.1.4/start.rpy.
ScriptError: Name (u'D:\\DCT_A_new_Journey_begin_1.1.3/game/Code/System_000_DCT_Setting/000_DCT_BG.rpy', 1531809295, 69) is defined twice, at Code - 1.1.4/System_000_DCT_Setting/000_DCT_BG.rpyc:2 and game/Code/System_000_DCT_Setting/000_DCT_BG.rpy:2.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-6.99.11-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "D:\renpy-6.99.11-sdk\renpy\main.py", line 358, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "D:\renpy-6.99.11-sdk\renpy\script.py", line 259, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "D:\renpy-6.99.11-sdk\renpy\script.py", line 738, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "D:\renpy-6.99.11-sdk\renpy\script.py", line 414, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'D:\\DCT_A_new_Journey_begin_1.1.3/game/Code/System_000_DCT_Setting/000_DCT_BG.rpy', 1531809295, 69) is defined twice, at Code - 1.1.4/System_000_DCT_Setting/000_DCT_BG.rpyc:2 and game/Code/System_000_DCT_Setting/000_DCT_BG.rpy:2.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.11.1749
 
